/*
This file exports the common packages required by the client.

It is used by build.js to to generate public/js/packages.js, and the packages
below are excluded from the browserify builds generated by
admin/server/middleware/browserify.js
*/
const keystonePackages = require('keystone/admin/client/packages');

const newPackages = [];

const packages = keystonePackages.concat(newPackages);

module.exports = packages;
